server:
  port: 8088
  servlet:
    context-path: /clams
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    #dev 开发环境  test 测试环境  prod 生产环境
    active: dev
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  datasource:
    url: ENC(EIbkObZZOUk2pFLhfE38mItJc9rG3awvJYPIc8clEcaGAVx5AhU/ybfQRmve1bUS+d1IroeEWJ296smK5Zb1l/kZQP1Qo6MU)
    username: ENC(5CmI6WlRLbj09pVwIxoknw==)
    password: ENC(KmXsfjzvRKVCGAqGdPDTAQ==)
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true

mybatis:
  mapper-locations: classpath:com/winconlab/clams/mapper/*.xml
  type-aliases-package: com.winconlab.clams.pojo
logging:
  config: classpath:logback-spring.xml


jasypt:
  encryptor:
    password: ljk
