server:
  port: 8088
  servlet:
    context-path: /clams
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    #dev 开发环境  test 测试环境  prod 生产环境
    active: prod
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  datasource:
    url: jdbc:mysql://119.29.160.254:3306/nnwrj?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true

mybatis:
  mapper-locations: classpath:com/winconlab/clams/mapper/*.xml
  type-aliases-package: com.winconlab.clams.pojo
logging:
  config: classpath:logback-spring.xml
  path: D:\log\clams

shiro:
  ehcache:
    #windows
    path: D:\develop\ehcache

